In [1]:
#pip install tensorflow

In [2]:
import pandas as pd
from ast import literal_eval
import numpy as np

df = pd.read_excel("AudioFeatures.xlsx")

In [3]:
df

,Signal,Language,Zero Crossings,Spectral Centroid,Onsets,Tempo
0,[1.1675724e-09 3.1484355e-08 1.0967056e-07 ......,Japanese,8448,2108.233582,18,143.554688
1,[0.04198965 0.04641543 0.05482003 ... 0.003945...,Japanese,8632,2268.836622,14,123.046875
2,[ 0.00070652 0.00178465 0.00204798 ... -0.08...,Japanese,9685,2477.925983,19,107.666016
3,[-0.03356273 0.00269012 0.03509961 ... 0.23...,Japanese,8711,2382.418681,17,112.347147
4,[0.25635257 0.24773552 0.23589143 ... 0.001000...,Japanese,12454,3022.306703,16,117.453835
...,...,...,...,...,...,...
2795,[-0.00671834 -0.00451336 -0.00589374 ... 0.02...,Spanish,2815,1063.769425,24,112.347147
2796,[ 0.03492408 0.03709995 0.03837612 ... -0.00...,Spanish,3405,1228.912212,17,123.046875
2797,[ 0.00133462 0.00020201 0.00163094 ... -0.01...,Spanish,5131,1884.406207,22,135.999178
2798,[-0.01553974 -0.01841803 -0.02212268 ... -0.01...,Spanish,4764,1638.904595,14,143.554688
2799,[-0.00946495 -0.00609279 -0.00321688 ... -0.07...,Spanish,2962,1250.900965,19,117.453835

In [4]:
features = df.iloc[:,2:]
features

      Zero Crossings  Spectral Centroid  Onsets       Tempo
0               8448        2108.233582      18  143.554688
1               8632        2268.836622      14  123.046875
2               9685        2477.925983      19  107.666016
3               8711        2382.418681      17  112.347147
4              12454        3022.306703      16  117.453835
...              ...                ...     ...         ...
2795            2815        1063.769425      24  112.347147
2796            3405        1228.912212      17  123.046875
2797            5131        1884.406207      22  135.999178
2798            4764        1638.904595      14  143.554688
2799            2962        1250.900965      19  117.453835

[2800 rows x 4 columns]

In [5]:
labels = [[num]*400 for num in range(len(set(df["Language"])))]
labels = np.array(labels).flatten()
labels

array([0, 0, 0, ..., 6, 6, 6])

In [6]:
featureVals = features.values
from sklearn.model_selection import train_test_split
feat, val_feat, labs, val_labs = train_test_split(featureVals, labels, test_size=0.1, random_state=10, shuffle=True, stratify=labels)

In [7]:
featureVals

array([[8448.        , 2108.23358239,   18.        ,  143.5546875 ],
       [8632.        , 2268.83662154,   14.        ,  123.046875  ],
       [9685.        , 2477.92598274,   19.        ,  107.66601562],
       ...,
       [5131.        , 1884.40620728,   22.        ,  135.99917763],
       [4764.        , 1638.90459478,   14.        ,  143.5546875 ],
       [2962.        , 1250.90096522,   19.        ,  117.45383523]])

In [ ]:
batch_size = 10  
num_epochs = 70
lr = 0.0001

In [6]:
import tensorflow as tf

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(12, input_dim=8, activation='relu'))
model.add(tf.keras.layers.Dense(8, activation='relu'))
model.add(tf.keras.layers.Dense(7, activation='sigmoid'))